import { NextRequest, NextResponse } from "next/server";
import { store } from "@/lib/store";
import { SESSION_COOKIE } from "@/lib/auth";
import { getUserBySession, clientIp } from "@/lib/session";

const KINDS = new Set(["offer", "answer", "ice-viewer", "ice-agent", "bye", "profile"]);

// WebRTC signaling for desktop sessions. Every row carries the owner's
// user_id; readers/writers only ever see their own rows. The session `code`
// is a 128-bit random single-use secret generated by the viewer.
export async function POST(req: NextRequest) {
  const user = await getUserBySession(req.cookies.get(SESSION_COOKIE)?.value);
  if (!user) return NextResponse.json({ error: "Not logged in." }, { status: 401 });
  let body: any = {};
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON." }, { status: 400 });
  }
  const code = String(body.code || "");
  const kind = String(body.kind || "");
  const payload = String(body.payload || "").slice(0, 20000);
  if (!/^[0-9a-f-]{8,64}$/i.test(code)) {
    return NextResponse.json({ error: "Bad session code." }, { status: 400 });
  }
  if (!KINDS.has(kind)) {
    return NextResponse.json({ error: "Bad signal kind." }, { status: 400 });
  }
  try {
    await store.postSignal({ code: code.toLowerCase(), user_id: user.id, kind, payload });
    return NextResponse.json({ ok: true });
  } catch (e: any) {
    return NextResponse.json({ error: e?.message || "Signal failed." }, { status: 503 });
  }
}

export async function GET(req: NextRequest) {
  const user = await getUserBySession(req.cookies.get(SESSION_COOKIE)?.value);
  if (!user) return NextResponse.json({ error: "Not logged in." }, { status: 401 });
  const url = new URL(req.url);
  const code = (url.searchParams.get("code") || "").toLowerCase();
  const after = Number(url.searchParams.get("after") || 0);
  if (!/^[0-9a-f-]{8,64}$/i.test(code)) {
    return NextResponse.json({ error: "Bad session code." }, { status: 400 });
  }
  try {
    const rows = await store.getSignals(code, user.id, after);
    return NextResponse.json({ signals: rows });
  } catch (e: any) {
    return NextResponse.json({ error: e?.message || "Signal poll failed." }, { status: 503 });
  }
}

export async function DELETE(req: NextRequest) {
  const user = await getUserBySession(req.cookies.get(SESSION_COOKIE)?.value);
  if (!user) return NextResponse.json({ error: "Not logged in." }, { status: 401 });
  const url = new URL(req.url);
  const code = (url.searchParams.get("code") || "").toLowerCase();
  if (code) {
    await store.deleteSignals(code, user.id);
    store.audit("desktop.close", code, user.id, clientIp(req));
  }
  return NextResponse.json({ ok: true });
}
